fix: List strings instead of enum objects as CLI options
Before:

```
$ meltano install v
Usage: meltano install [OPTIONS] [[extractor|loader|transform|orchestrator|tra
                       nsformer|file|utility|mapper|mapping|extractors|loaders
                       |transforms|orchestrators|transformers|files|utilities|
                       mappers|mappings]] [PLUGIN_NAME]...
Try 'meltano install --help' for help.

Error: Invalid value for '[[extractor|loader|transform|orchestrator|transformer|file|utility|mapper|mapping|extractors|loaders|transforms|orchestrators|transformers|files|utilities|mappers|mappings]]': 'v' is not one of 'extractor', 'loader', 'transform', 'orchestrator', 'transformer', 'file', 'utility', 'mapper', 'mapping', <PluginType.EXTRACTORS: 'extractors'>, <PluginType.LOADERS: 'loaders'>, <PluginType.TRANSFORMS: 'transforms'>, <PluginType.ORCHESTRATORS: 'orchestrators'>, <PluginType.TRANSFORMERS: 'transformers'>, <PluginType.FILES: 'files'>, <PluginType.UTILITIES: 'utilities'>, <PluginType.MAPPERS: 'mappers'>, <PluginType.MAPPINGS: 'mappings'>.
```

After:

```
meltano install v
Usage: meltano install [OPTIONS] [[extractor|extractors|loader|loaders|transfo
                       rm|transforms|orchestrator|orchestrators|transformer|tr
                       ansformers|file|files|utility|utilities|mapper|mappers|
                       mapping|mappings]] [PLUGIN_NAME]...
Try 'meltano install --help' for help.

Error: Invalid value for '[[extractor|extractors|loader|loaders|transform|transforms|orchestrator|orchestrators|transformer|transformers|file|files|utility|utilities|mapper|mappers|mapping|mappings]]': 'v' is not one of 'extractor', 'extractors', 'loader', 'loaders', 'transform', 'transforms', 'orchestrator', 'orchestrators', 'transformer', 'transformers', 'file', 'files', 'utility', 'utilities', 'mapper', 'mappers', 'mapping', 'mappings'.
```